### ISSUE TITLE
Add `pullback` for reducers

### ISSUE THREAD

**Issue by peter-tomaselli** [wayfair/prelude#7]
Pointfree has a [good pitch](https://www.pointfree.co/blog/posts/22-some-news-about-contramap) for renaming `contramap` (which we have on reducers) to `pullback`. We could either rename our `contramap` to `pullback`, or have both.

**Comment by klundberg** [comment]
I think renaming to pullback makes sense. Having two names for the same thing might be a bit confusing. This hasn't had a 1.0 release yet so API breaking changes should be fine
